test:
  mysql41: 9307
development: &my_settings
  enable_star: true
  min_prefix_len: 0
  min_infix_len: 1
  min_word_len: 1
  charset_type: utf-8
  morphology: stem_ru
production:
  enable_star: true
  min_prefix_len: 0
  min_infix_len: 1
  min_word_len: 1
  charset_type: utf-8
  morphology: stem_ru, stem_en
  mysql41: 9307
  pid_file: /home/deployer/asky/shared/tmp/pids/searchd.pid
  indices_location: db/sphinx
  configuration_file: config/production.sphinx.conf
  binlog_path: binlog
